<Project Sdk="Godot.NET.Sdk/3.2.3">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>nuclearnation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".gitignore" />
    <Content Include=".mill-version" />
    <Content Include="build.sc" />
    <Content Include="buildandrunwithdebugopts.sh" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\ControlledBy$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\ControlledBy.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapCellData.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapCoordsGenerator.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapData.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$$anon$1.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$$anon$2.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$$anon$3.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$ActorMapCoords$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$ActorMapCoords.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$CityInfo$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$CityInfo.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$CoveredAreaInfo$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$CoveredAreaInfo.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$MapClickInfo$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$MapClickInfo.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$MapLocation.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$RaiderCampInfo$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$RaiderCampInfo.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$RuinsInfo$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$RuinsInfo.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$Technology$.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen$Technology.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\MapScreen.class" />
    <Content Include="core\build\classes\scala\main\com\anton\nuclearnation\NuclearNation.class" />
    <Content Include="core\build\libs\core-1.0.jar" />
    <Content Include="core\build\tmp\jar\MANIFEST.MF" />
    <Content Include="core\build\tmp\scala\compilerAnalysis\compileScala.analysis" />
    <Content Include="core\build\tmp\scala\compilerAnalysis\compileScala.analysis.relations" />
    <Content Include="core\build\tmp\scala\compilerAnalysis\compileScala.mapping" />
    <Content Include="core\out\production\resources\bucket.png" />
    <Content Include="core\out\production\resources\drop.wav" />
    <Content Include="core\out\production\resources\droplet.png" />
    <Content Include="core\out\production\resources\rain.mp3" />
    <Content Include="core\resources\actionMix\expeditionOutcome.png" />
    <Content Include="core\resources\cardGameScreen\brokenMachinery.png" />
    <Content Include="core\resources\cardGameScreen\monster.png" />
    <Content Include="core\resources\cardGameScreen\rubble.png" />
    <Content Include="core\resources\city\cityPicture.png" />
    <Content Include="core\resources\data\commodore64\preview.gif" />
    <Content Include="core\resources\data\commodore64\raw\blue.png" />
    <Content Include="core\resources\data\commodore64\raw\button-down.9.png" />
    <Content Include="core\resources\data\commodore64\raw\button.9.png" />
    <Content Include="core\resources\data\commodore64\raw\check-box-off.png" />
    <Content Include="core\resources\data\commodore64\raw\check-box.png" />
    <Content Include="core\resources\data\commodore64\raw\commodore-64.fnt" />
    <Content Include="core\resources\data\commodore64\raw\commodore-64.png" />
    <Content Include="core\resources\data\commodore64\raw\cursor-black.9.png" />
    <Content Include="core\resources\data\commodore64\raw\cursor.9.png" />
    <Content Include="core\resources\data\commodore64\raw\dialog.9.png" />
    <Content Include="core\resources\data\commodore64\raw\grey.png" />
    <Content Include="core\resources\data\commodore64\raw\horizontal-split-pane.9.png" />
    <Content Include="core\resources\data\commodore64\raw\light-blue.png" />
    <Content Include="core\resources\data\commodore64\raw\list.9.png" />
    <Content Include="core\resources\data\commodore64\raw\minus.png" />
    <Content Include="core\resources\data\commodore64\raw\music-off.png" />
    <Content Include="core\resources\data\commodore64\raw\music.png" />
    <Content Include="core\resources\data\commodore64\raw\plus.png" />
    <Content Include="core\resources\data\commodore64\raw\progress-bar-knob.9.png" />
    <Content Include="core\resources\data\commodore64\raw\progress-bar.9.png" />
    <Content Include="core\resources\data\commodore64\raw\radio-button-off.png" />
    <Content Include="core\resources\data\commodore64\raw\radio-button.9.png" />
    <Content Include="core\resources\data\commodore64\raw\radio-button.png" />
    <Content Include="core\resources\data\commodore64\raw\README.md" />
    <Content Include="core\resources\data\commodore64\raw\scroll-bar-horizontal-knob.9.png" />
    <Content Include="core\resources\data\commodore64\raw\scroll-bar-vertical-knob.9.png" />
    <Content Include="core\resources\data\commodore64\raw\scroll-bar.9.png" />
    <Content Include="core\resources\data\commodore64\raw\slider-knob.png" />
    <Content Include="core\resources\data\commodore64\raw\slider.png" />
    <Content Include="core\resources\data\commodore64\raw\sound-off.png" />
    <Content Include="core\resources\data\commodore64\raw\sound.png" />
    <Content Include="core\resources\data\commodore64\raw\touchpad-knob.png" />
    <Content Include="core\resources\data\commodore64\raw\touchpad.png" />
    <Content Include="core\resources\data\commodore64\raw\vertical-split-pane.9.png" />
    <Content Include="core\resources\data\commodore64\raw\white.png" />
    <Content Include="core\resources\data\commodore64\raw\window.9.png" />
    <Content Include="core\resources\data\commodore64\README.md" />
    <Content Include="core\resources\data\commodore64\skin\commodore-64.fnt" />
    <Content Include="core\resources\data\commodore64\skin\uiskin.atlas" />
    <Content Include="core\resources\data\commodore64\skin\uiskin.json" />
    <Content Include="core\resources\data\commodore64\skin\uiskin.png" />
    <Content Include="core\resources\data\commodore64\style-guide.png" />
    <Content Include="core\resources\desert_tile.png" />
    <Content Include="core\resources\expedition.png" />
    <Content Include="core\resources\fog_of_war_tile.png" />
    <Content Include="core\resources\fonts\lunchtime-doubly-so\license.txt" />
    <Content Include="core\resources\fonts\lunchtime-doubly-so\lunchds.ttf" />
    <Content Include="core\resources\militaryCaravan.png" />
    <Content Include="core\resources\music\POL-dark-crossing-short.mp3" />
    <Content Include="core\resources\music\POL-secret-labs-short.mp3" />
    <Content Include="core\resources\music\POL-torn-short.mp3" />
    <Content Include="core\resources\raider-facing-left.png" />
    <Content Include="core\resources\raider_camp.png" />
    <Content Include="core\resources\ruined-building.png" />
    <Content Include="core\resources\soldier-facing-left.png" />
    <Content Include="core\resources\soldier-facing-right.png" />
    <Content Include="core\resources\town.png" />
    <Content Include="core\resources\tradeCaravan.png" />
    <Content Include="core\resources\unitConstruction\commandoUnit.png" />
    <Content Include="core\resources\unitConstruction\crossedSwords.png" />
    <Content Include="core\resources\unitConstruction\engineerUnit.png" />
    <Content Include="core\resources\unitConstruction\questionMark.png" />
    <Content Include="core\resources\unitConstruction\scientistUnit.png" />
    <Content Include="core\resources\unitConstruction\soldierUnit.png" />
    <Content Include="core\resources\unitConstruction\spyKeyhole.png" />
    <Content Include="core\resources\unitConstruction\spyUnit.png" />
    <Content Include="core\src\com\anton\nuclearnation\ControlledBy.scala" />
    <Content Include="core\src\com\anton\nuclearnation\MapCellData.scala" />
    <Content Include="core\src\com\anton\nuclearnation\MapCoordsGenerator.scala" />
    <Content Include="core\src\com\anton\nuclearnation\MapData.scala" />
    <Content Include="core\src\com\anton\nuclearnation\MapScreen.scala" />
    <Content Include="core\src\com\anton\nuclearnation\NuclearNation.scala" />
    <Content Include="desktop\build\classes\java\main\com\anton\nuclearnation\desktop\DesktopLauncher.class" />
    <Content Include="desktop\build\tmp\compileJava\source-classes-mapping.txt" />
    <Content Include="desktop\src\main\com\anton\nuclearnation\desktop\DesktopLauncher.java" />
    <Content Include="mill" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <HintPath>packages\FSharp.Core.4.5.2\lib\net45\FSharp.Core.dll</HintPath>
    </Reference>
    <Reference Include="FSharp.Core.resources, Version=4.5.0.0, Culture=zh-Hant, PublicKeyToken=b03f5f7f11d50a3a">
      <HintPath>packages\FSharp.Core.4.5.2\lib\net45\FSharp.Core.resources.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="FS\FS.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="core\build\generated\sources\annotationProcessor\scala\main" />
    <Folder Include="core\build\tmp\compileScala" />
    <Folder Include="core\build\tmp\scala\classfileBackup" />
    <Folder Include="desktop\build\generated\sources\annotationProcessor\java\main" />
    <Folder Include="desktop\build\generated\sources\headers\java\main" />
  </ItemGroup>
</Project>